### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by naelarokha** [Tuna-Terps/SeaShell-greyhack-game#10]
Greyhack v0.8
SeaShell v1.0.7

1. when running "ss".
Runtime error: key not found: 'get_name' not found in map [core line 185].

2. building the rainbow tables. 
Runtime error: type error (while attempting to look up path) [line 18]. | warning: did not get a response from builder.

3. building the rainbow tables. 
Runtime error: undefined identifier: 'brute1' is unknown in this context [line 14]. | warning: did not get a response from builder.

**Comment by Tuna-Terps** [comment]
Hello there, some issues appear to be the result of the installation process. 
Firstly, please redownload core.gs, i have pushed an update to it but i believe that is not the issue with this first error. 

If installer gives issues, manual installation is very straightforward. Once you have ss installed and running whether using installer or not, you can use the command -cfg -ccd to build the entire user cache if you did not do so already with installer

Seashell has each step of installer built into it as well, for the rainbow tables, you will want to delete brute1.src - brute7 , then in seashell use command -cfg -h -p  this is what you will use to rebuild the rainbow tables. The error you describe is one i have seen countless times from improper saving of the files.
