### ISSUE TITLE
Proxchain amount

### ISSUE THREAD

**Issue by bapking** [Tuna-Terps/SeaShell-greyhack-game#16]
I could be mistaken but I think proxchain -d is running through multiple connections even when 1 is specified. I tried with both proxchain -d ?1 & proxchain -d 1. I've attached the outputs here.
[proxchain d 1.txt](https://github.com/user-attachments/files/15995775/proxchain.d.1.txt)
[proxchain d q1.txt](https://github.com/user-attachments/files/15995781/proxchain.d.q1.txt)

**Comment by Tuna-Terps** [comment]
dirty tunnel will always attempt to find an initial launch point that is in addition to the amount of machines specified, ive also adjusted the check to eliminate false negatives in the loop.
