### ISSUE TITLE
im new

### ISSUE THREAD

**Issue by f2ypr** [Tuna-Terps/SeaShell-greyhack-game#4]
hi i dont now how to put it in the game can anyone help me

**Comment by Tuna-Terps** [comment]
please follow the instructions in the readme. Using the installer script is my recommended approach

**Comment by f2ypr** [comment]
> please follow the instructions in the readme. Using the installer script is my recommended approach

do you now what i do when i get    Specify user for builder's path > 
 i get error everytime
