### ISSUE TITLE
[Action required] Specify user for builder's path >

### ISSUE THREAD

**Issue by f2ypr** [Tuna-Terps/SeaShell-greyhack-game#5]
![image](https://github.com/Tuna-Terps/SeaShell-greyhack-game/assets/145709231/409b7f8d-3852-46ff-bd65-c1bf80319fcf)

**Comment by Tuna-Terps** [comment]
https://github.com/Tuna-Terps/SeaShell-greyhack-game/commit/bf1156d7cd192866a2a2a3442ddb99044bf659dc
