### ISSUE TITLE
Notable issues with the installer

### ISSUE THREAD

**Issue by george2781** [Tuna-Terps/SeaShell-greyhack-game#7]
The installer script is better than it was before, but it still has a couple issues and/or quirks that would trip up a new user pretty easily

Namely
- `npc` breaks when seashell is created through the installer, it is not known why it does this but it does
- `cargo.gs` needs the user to manually edit it for it to actually compile, since it is hardcoded to point to /home/2NA/src for it's `import_code` segments
- References to the NPM API wrapper as seen in `main.src` are nowhere to be found, albeit this isn't that much of an issue for the time being considering the NPM API isn't online yet in the new public wipe.

Overall I would say this tool is still really strong, even if a couple quirks need working out, keep up the great work Tuna!

**Comment by Tuna-Terps** [comment]
Thank you for your report, ive gone ahead and addressed the cargo.src file, and will push some changes to main.src as well as handle the offline npm api; Appreciate the kind words
